# Generated by Django 2.2.12 on 2023-03-02 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='kcpModulesManage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('busmodule', models.CharField(default='', max_length=500, verbose_name='业务模块')),
                ('status', models.CharField(choices=[('1', '启用'), ('0', '禁用')], default='1', max_length=10, verbose_name='状态')),
                ('createTime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updateTime', models.DateTimeField(auto_now_add=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'helloCloud',
                'verbose_name_plural': 'helloCloud',
            },
        ),
    ]
