# Generated by Django 2.2.12 on 2023-03-22 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busModule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='oneModulesManage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('busmodule', models.CharField(default='', max_length=500, verbose_name='业务模块')),
                ('status', models.CharField(choices=[('0', '禁用'), ('1', '启用')], default='1', max_length=10, verbose_name='状态')),
                ('createTime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updateTime', models.DateTimeField(auto_now_add=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'one',
                'verbose_name_plural': 'one',
            },
        ),
        migrations.AlterModelOptions(
            name='kcpmodulesmanage',
            options={'verbose_name': 'kcp', 'verbose_name_plural': 'kcp'},
        ),
        migrations.AlterField(
            model_name='kcpmodulesmanage',
            name='status',
            field=models.CharField(choices=[('0', '禁用'), ('1', '启用')], default='1', max_length=10, verbose_name='状态'),
        ),
    ]
