# Generated by Django 2.2.12 on 2023-03-02 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='projectGroupManage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectGroup', models.CharField(default='', max_length=20, verbose_name='项目组')),
                ('addTime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modifyTime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '项目组列表',
                'verbose_name_plural': '项目组列表',
            },
        ),
        migrations.CreateModel(
            name='projectManage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(default='', max_length=50, verbose_name='项目')),
                ('status', models.CharField(choices=[('1', '启用'), ('0', '禁用')], default='1', max_length=10, verbose_name='状态')),
                ('caseRunList', models.CharField(choices=[('testCaseVeRun', 'testCaseVeRun'), ('testCaseGroupPlatformRun', 'testCaseGroupPlatformRun'), ('testCaseCpRun', 'testCaseCpRun'), ('testCaseCloudAssistantRun', 'testCaseCloudAssistantRun'), ('testCaseRoleParkRun', 'testCaseRoleParkRun'), ('testCasePcRun', 'testCasePcRun'), ('testCaseCityPlatformRun', 'testCaseCityPlatformRun'), ('testCaseVisitorAuthMobileRun', 'testCaseVisitorAuthMobileRun'), ('testCaseParkRun', 'testCaseParkRun'), ('testCasePostPaidRun', 'testCasePostPaidRun'), ('testCaseNonStandardRun', 'testCaseNonStandardRun'), ('testCaseKTBrainDistributedRun', 'testCaseKTBrainDistributedRun'), ('testCaseLotLabelRun', 'testCaseLotLabelRun'), ('testCaseCouponMobileRun', 'testCaseCouponMobileRun'), ('testCaseHardwarePlatformRun', 'testCaseHardwarePlatformRun'), ('testCaseAdverPlatformRun', 'testCaseAdverPlatformRun'), ('testCaseKTBrainRun', 'testCaseKTBrainRun')], max_length=50, verbose_name='用例执行列表')),
                ('caseReRunList', models.CharField(choices=[('testCaseVeReRun', 'testCaseVeReRun'), ('testCaseRoleParkReRun', 'testCaseRoleParkReRun'), ('testCaseHardwarePlatformReRun', 'testCaseHardwarePlatformReRun'), ('testCaseAdverPlatformReRun', 'testCaseAdverPlatformReRun'), ('testCaseVisitorAuthMobileReRun', 'testCaseVisitorAuthMobileReRun'), ('testCaseKTBrainReRun', 'testCaseKTBrainReRun'), ('testCaseCityPlatformReRun', 'testCaseCityPlatformReRun'), ('testCaseCouponMobileReRun', 'testCaseCouponMobileReRun'), ('testCaseKTBrainDistributedReRun', 'testCaseKTBrainDistributedReRun'), ('testCaseLotLabelReRun', 'testCaseLotLabelReRun'), ('testCaseParkReRun', 'testCaseParkReRun'), ('testCaseGroupPlatformReRun', 'testCaseGroupPlatformReRun'), ('testCasePostPaidReRun', 'testCasePostPaidReRun'), ('testCasePcReRun', 'testCasePcReRun'), ('testCaseNonStandardReRun', 'testCaseNonStandardReRun'), ('testCaseCpReRun', 'testCaseCpReRun'), ('testCaseCloudAssistantReRun', 'testCaseCloudAssistantReRun')], max_length=50, verbose_name='失败重跑用例执行列表')),
                ('testBusServer', models.CharField(choices=[('cloudAssistantBoard', 'cloudAssistantBoard'), ('adverPlatformBoard', 'adverPlatformBoard'), ('lotLabelBoard', 'lotLabelBoard'), ('roleParkBoard', 'roleParkBoard'), ('brainDistributedBoard', 'brainDistributedBoard'), ('carServer', 'carServer'), ('brainBoard', 'brainBoard'), ('pcServer', 'pcServer'), ('veBoard', 'veBoard'), ('cityPlatformBoard', 'cityPlatformBoard'), ('parkBoard', 'parkBoard'), ('hardwarePlatformBoard', 'hardwarePlatformBoard'), ('couponBoard', 'couponBoard'), ('groupPlatformBoard', 'groupPlatformBoard'), ('postPaidBoard', 'postPaidBoard'), ('visitorAuthBoard', 'visitorAuthBoard'), ('nonStandardBoard', 'nonStandardBoard')], max_length=50, verbose_name='业务测试服务')),
                ('addTime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modifyTime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('projectGroup', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='projects.projectGroupManage', verbose_name='项目组')),
            ],
            options={
                'verbose_name': '项目列表',
                'verbose_name_plural': '项目列表',
            },
        ),
    ]
