# Generated by Django 2.2.12 on 2023-03-02 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmanage',
            name='caseReRunList',
            field=models.CharField(choices=[('testCaseLotLabelReRun', 'testCaseLotLabelReRun'), ('testCaseGroupPlatformReRun', 'testCaseGroupPlatformReRun'), ('testCaseCloudAssistantReRun', 'testCaseCloudAssistantReRun'), ('testCaseVisitorAuthMobileReRun', 'testCaseVisitorAuthMobileReRun'), ('testCaseVeReRun', 'testCaseVeReRun'), ('testCaseCityPlatformReRun', 'testCaseCityPlatformReRun'), ('testCasePcReRun', 'testCasePcReRun'), ('testCaseKTBrainReRun', 'testCaseKTBrainReRun'), ('testCaseRoleParkReRun', 'testCaseRoleParkReRun'), ('testCasePostPaidReRun', 'testCasePostPaidReRun'), ('testCaseHardwarePlatformReRun', 'testCaseHardwarePlatformReRun'), ('testCaseKTBrainDistributedReRun', 'testCaseKTBrainDistributedReRun'), ('testCaseCpReRun', 'testCaseCpReRun'), ('testCaseAdverPlatformReRun', 'testCaseAdverPlatformReRun'), ('testCaseCouponMobileReRun', 'testCaseCouponMobileReRun'), ('testCaseNonStandardReRun', 'testCaseNonStandardReRun'), ('testCaseParkReRun', 'testCaseParkReRun')], max_length=50, verbose_name='失败重跑用例执行列表'),
        ),
        migrations.AlterField(
            model_name='projectmanage',
            name='caseRunList',
            field=models.CharField(choices=[('testCasePcRun', 'testCasePcRun'), ('testCaseGroupPlatformRun', 'testCaseGroupPlatformRun'), ('testCaseLotLabelRun', 'testCaseLotLabelRun'), ('testCaseVeRun', 'testCaseVeRun'), ('testCasePostPaidRun', 'testCasePostPaidRun'), ('testCaseKTBrainDistributedRun', 'testCaseKTBrainDistributedRun'), ('testCaseNonStandardRun', 'testCaseNonStandardRun'), ('testCaseAdverPlatformRun', 'testCaseAdverPlatformRun'), ('testCaseCloudAssistantRun', 'testCaseCloudAssistantRun'), ('testCaseKTBrainRun', 'testCaseKTBrainRun'), ('testCaseVisitorAuthMobileRun', 'testCaseVisitorAuthMobileRun'), ('testCaseCouponMobileRun', 'testCaseCouponMobileRun'), ('testCaseHardwarePlatformRun', 'testCaseHardwarePlatformRun'), ('testCaseCityPlatformRun', 'testCaseCityPlatformRun'), ('testCaseParkRun', 'testCaseParkRun'), ('testCaseCpRun', 'testCaseCpRun'), ('testCaseRoleParkRun', 'testCaseRoleParkRun')], max_length=50, verbose_name='用例执行列表'),
        ),
        migrations.AlterField(
            model_name='projectmanage',
            name='testBusServer',
            field=models.CharField(choices=[('cityPlatformBoard', 'cityPlatformBoard'), ('postPaidBoard', 'postPaidBoard'), ('lotLabelBoard', 'lotLabelBoard'), ('nonStandardBoard', 'nonStandardBoard'), ('brainDistributedBoard', 'brainDistributedBoard'), ('hardwarePlatformBoard', 'hardwarePlatformBoard'), ('cloudAssistantBoard', 'cloudAssistantBoard'), ('couponBoard', 'couponBoard'), ('adverPlatformBoard', 'adverPlatformBoard'), ('visitorAuthBoard', 'visitorAuthBoard'), ('brainBoard', 'brainBoard'), ('parkBoard', 'parkBoard'), ('groupPlatformBoard', 'groupPlatformBoard'), ('roleParkBoard', 'roleParkBoard'), ('carServer', 'carServer'), ('veBoard', 'veBoard'), ('pcServer', 'pcServer')], max_length=50, verbose_name='业务测试服务'),
        ),
    ]
