# Generated by Django 2.2.12 on 2023-03-10 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20230302_1417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectmanage',
            name='caseReRunList',
        ),
        migrations.RemoveField(
            model_name='projectmanage',
            name='caseRunList',
        ),
        migrations.RemoveField(
            model_name='projectmanage',
            name='testBusServer',
        ),
    ]
