# Generated by Django 2.2.12 on 2023-03-22 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20230310_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmanage',
            name='status',
            field=models.CharField(choices=[('0', '禁用'), ('1', '启用')], default='1', max_length=10, verbose_name='状态'),
        ),
    ]
