# Generated by Django 2.2.12 on 2023-03-02 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testcases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcasehcmanage',
            name='caseLevel',
            field=models.CharField(choices=[('3', '中'), ('5', '无关紧要'), ('2', '高'), ('1', '紧急'), ('4', '低')], max_length=10, verbose_name='等级'),
        ),
        migrations.AlterField(
            model_name='testcasehcmanage',
            name='caseType',
            field=models.CharField(choices=[('1', '冒烟测试'), ('2', '回归测试')], max_length=10, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='testcasehcrun',
            name='runType',
            field=models.CharField(choices=[('3', '回归测试'), ('2', '冒烟测试'), ('4', '按等级测试'), ('1', '自定义')], default='1', max_length=10, verbose_name='执行类型'),
        ),
    ]
