# Generated by Django 2.2.12 on 2023-03-22 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testcases', '0003_auto_20230310_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testCasesKcpManage',
            name='caseLevel',
            field=models.CharField(choices=[('3', '低'), ('1', '高'), ('2', '中')], max_length=10, verbose_name='等级'),
        ),
        migrations.AlterField(
            model_name='testCasesKcpManage',
            name='caseType',
            field=models.CharField(choices=[('1', '冒烟测试'), ('2', '回归测试')], max_length=10, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='testCasesKcpManage',
            name='status',
            field=models.CharField(choices=[('0', '禁用'), ('1', '启用')], max_length=10, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='testCasesKcpRun',
            name='runType',
            field=models.CharField(choices=[('2', '全部'), ('1', '冒烟测试')], default='2', max_length=10, verbose_name='执行类型'),
        ),
    ]
