# Generated by Django 2.2.12 on 2023-03-22 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20230322_1104'),
        ('busModule', '0002_auto_20230322_1104'),
        ('testcases', '0004_auto_20230322_1104'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testcaseskcpmanage',
            options={'verbose_name': 'kcp测试用例', 'verbose_name_plural': 'kcp测试用例'},
        ),
        migrations.AlterField(
            model_name='testcaseskcpmanage',
            name='caseLevel',
            field=models.CharField(choices=[('2', '中'), ('1', '高'), ('3', '低')], max_length=10, verbose_name='等级'),
        ),
        migrations.AlterField(
            model_name='testcaseskcprun',
            name='runType',
            field=models.CharField(choices=[('1', '冒烟测试'), ('2', '全部')], default='2', max_length=10, verbose_name='执行类型'),
        ),
        migrations.CreateModel(
            name='testCasesOneRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskId', models.IntegerField(default=0, verbose_name='任务Id')),
                ('busmodule', models.CharField(max_length=500, verbose_name='业务模块')),
                ('caseNo', models.CharField(default='', max_length=100, verbose_name='用例编号')),
                ('casename', models.CharField(default='', max_length=500, verbose_name='用例标题')),
                ('caseType', models.CharField(max_length=50, verbose_name='用例类型')),
                ('caseLevel', models.CharField(max_length=50, verbose_name='用例等级')),
                ('caseFile', models.CharField(max_length=100, verbose_name='脚本文件')),
                ('caseModule', models.CharField(default='', max_length=100, verbose_name='类名')),
                ('casePcFunction', models.CharField(max_length=100, verbose_name='函数')),
                ('runType', models.CharField(choices=[('1', '冒烟测试'), ('2', '全部')], default='2', max_length=10, verbose_name='执行类型')),
                ('opUser', models.CharField(max_length=50, verbose_name='操作用户')),
                ('addTime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('project', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='projects.projectManage', verbose_name='项目')),
                ('projectGroup', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='projects.projectGroupManage', verbose_name='项目组')),
            ],
            options={
                'verbose_name': '用例执行',
                'verbose_name_plural': '用例执行',
            },
        ),
        migrations.CreateModel(
            name='testCasesOneManage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caseNo', models.CharField(default='', max_length=100, unique=True, verbose_name='用例编号')),
                ('casename', models.CharField(max_length=500, verbose_name='用例标题')),
                ('caseType', models.CharField(choices=[('1', '冒烟测试'), ('2', '回归测试')], max_length=10, verbose_name='类型')),
                ('caseLevel', models.CharField(choices=[('2', '中'), ('1', '高'), ('3', '低')], max_length=10, verbose_name='等级')),
                ('caseFile', models.CharField(max_length=100, verbose_name='脚本文件')),
                ('caseModule', models.CharField(default='', max_length=100, verbose_name='类名')),
                ('casePcFunction', models.CharField(max_length=100, verbose_name='函数')),
                ('status', models.CharField(choices=[('0', '禁用'), ('1', '启用')], max_length=10, verbose_name='状态')),
                ('addTime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modifyTime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('busmodule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='busModule.oneModulesManage', verbose_name='业务模块')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.projectManage', verbose_name='项目')),
                ('projectGroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.projectGroupManage', verbose_name='项目组')),
            ],
            options={
                'verbose_name': 'one测试用例',
                'verbose_name_plural': 'one测试用例',
            },
        ),
    ]
