# Generated by Django 2.2.12 on 2023-03-02 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='runTaskManage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskName', models.CharField(blank=True, max_length=200, null=True, verbose_name='任务名称')),
                ('casesTotal', models.CharField(blank=True, max_length=20, null=True, verbose_name='用例数')),
                ('projectGroup_id', models.IntegerField(blank=True, null=True, verbose_name='项目组')),
                ('project_id', models.IntegerField(blank=True, null=True, verbose_name='项目')),
                ('taskRunFlag', models.CharField(blank=True, max_length=10, null=True, verbose_name='任务状态')),
                ('optUser', models.CharField(blank=True, max_length=10, null=True, verbose_name='操作人')),
                ('runMode', models.CharField(blank=True, max_length=10, null=True, verbose_name='运行模式')),
                ('runNum', models.IntegerField(blank=True, null=True, verbose_name='次数')),
                ('runTime', models.CharField(blank=True, max_length=50, null=True, verbose_name='运行时间')),
                ('reRunFlag', models.CharField(blank=True, max_length=50, null=True, verbose_name='是否失败重跑')),
                ('successedTotal', models.IntegerField(default=0, verbose_name='成功用例数')),
                ('failedTotal', models.IntegerField(default=0, verbose_name='失败用例数')),
                ('pendingTotal', models.IntegerField(default=0, verbose_name='待执行用例数')),
                ('process', models.CharField(default='0.00%', max_length=50, verbose_name='进度')),
                ('ratio', models.CharField(blank=True, max_length=50, null=True, verbose_name='通过率')),
                ('isDisplayReRun', models.CharField(blank=True, max_length=50, null=True, verbose_name='是否显示失败重跑')),
                ('createTime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modifyTime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '任务列表',
                'verbose_name_plural': '任务列表',
            },
        ),
    ]
